apiVersion: v1
description: A Helm chart to deploy the gardener-extension-admission-ironcore-metal application related resources
name: gardener-extension-admission-ironcore-metal-application
version: 0.1.0
sources:
- https://github.com/ironcore-dev/gardener-extension-provider-ironcore-metal
